name: C/C++ CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  release:
    runs-on: ${{ matrix.builder }}

    strategy:
      matrix:
        include:
          - builder: ubuntu-latest
            platform: linux/amd64
          - builder: buildjet-8vcpu-ubuntu-2204-arm
            platform: linux/arm64
            
    steps:
    - uses: actions/checkout@v3
    - name: "update"
      run: sudo apt update && sudo apt upgrade -y 
    - name: "install dependecies"
      run: sudo apt install -y build-essential cmake libboost-all-dev
    - name: "install dependecies"
      run: sudo apt install -y libasound2-dev libpulse-dev libvorbisidec-dev libvorbis-dev libopus-dev libflac-dev libsoxr-dev alsa-utils libavahi-client-dev avahi-daemon libexpat1-dev
    - name: "Create build directory and run CMake"
      run: cmake -S . -B build -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_CLIENT=OFF
    - name: "Build Project" 
      run: cmake --build build --target all --config Release -- -j4
    - name: "Rename binary"
      run: mv bin/snapserver bin/snapserver-${{ matrix.platform }}
